{{- $privateClientSecret := (randAlpha 16) | b64enc | quote }}
{{- $storageSecretPassword := (randAlpha 16) | b64enc | quote }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace "dex-secret") }}
{{- if $secret }}
{{- $privateClientSecret = index $secret.data "privateClientSecret" | default $privateClientSecret }}
{{- $storageSecretPassword = index $secret.data "dexStorageUserPassword" | default $storageSecretPassword }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: dex-secret
  namespace: {{ .Release.Namespace }}
data:
  privateClientSecret: {{ $privateClientSecret }}
  dexStorageUserPassword: {{ $storageSecretPassword }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dex
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.dexidp.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ .Values.serviceName }}
  namespace: flux-system
spec:
  targetNamespace: {{ .Release.Namespace }}
  interval: 1m
  chart:
    spec:
      chart: dex
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
      version: 0.18.0
  values:
    config:
      issuer: "https://{{ .Values.domain.main }}/dex"
      staticClients:
        - id: {{ .Values.publicClientId}}
          name: 'Public Client'
          redirectURIs:
            - 'https://{{ .Values.domain.main }}/callback'
            - 'http://localhost:3000/callback'
          public: true
        - id: {{ .Values.privateClientId}}
          name: 'Private Client'
          redirectURIs:
            - 'https://{{ .Values.domain.main }}/callback'
          secret: {{ $privateClientSecret}}
      staticPasswords:
        - email: "admin@example.com"
          hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
          username: "admin"
          userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
      enablePasswordDB: true
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: {{ .Values.connectors.github.clientID }}
            clientSecret: {{ .Values.connectors.github.clientSecret }}
            redirectURI: 'https://{{ .Values.domain.main }}/dex/callback'
            loadAllGroups: false
            useLoginAsID: false
      expiry:
        deviceRequests: "5m"
        signingKeys: "6h"
        idTokens: "24h"
        refreshTokens:
          reuseInterval: "3s"
          validIfNotUsedFor: "2160h" # 90 days
          absoluteLifetime: "3960h" # 165 days
      logger:
        level: "debug"
        format: "text" # can also be "json"
      storage:
        type: postgres
        config:
          host: {{ .Values.postgres.name }}.{{ .Release.Namespace }}.svc.cluster.local
          port: 5432
          database: dex
          user: dex_service
          password: {{ $storageSecretPassword | b64dec }}
          ssl:
            mode: "disable"
      oauth2:
        passwordConnector: local