{{- $workspaceServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $authServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $costEstimatorJobUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $subscriptionUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $pennywiseUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $informationUserPassword := (randAlpha 16) | b64enc | quote }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace "postgres-secret") }}
{{- if $secret }}
{{- $workspaceServiceUserPassword = index $secret.data "workspaceServiceUserPassword" | default $workspaceServiceUserPassword }}
{{- $authServiceUserPassword = index $secret.data "authServiceUserPassword" | default $authServiceUserPassword }}
{{- $costEstimatorJobUserPassword = index $secret.data "costEstimatorJobUserPassword" | default $costEstimatorJobUserPassword}}
{{- $subscriptionUserPassword = index $secret.data "subscriptionUserPassword" | default $subscriptionUserPassword}}
{{- $pennywiseUserPassword = index $secret.data "pennywiseUserPassword" | default $pennywiseUserPassword }}
{{- $informationUserPassword = index $secret.data "informationUserPassword" | default $informationUserPassword }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  workspaceServiceUserPassword: {{ $workspaceServiceUserPassword }}
  pennywiseUserPassword: {{ $pennywiseUserPassword }}
  authServiceUserPassword: {{ $authServiceUserPassword }}
  costEstimatorJobUserPassword: {{ $costEstimatorJobUserPassword }}
  subscriptionUserPassword: {{ $subscriptionUserPassword }}
  informationUserPassword: {{ $informationUserPassword }}