apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-pass-nginx-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;

        location /{{ .Release.Namespace }}/integration {
          rewrite ^/{{ .Release.Namespace }}/integration(.*) /integration$1 break;

          proxy_pass http://integration-service.{{ .Release.Namespace }}.svc.cluster.local:8000;
          proxy_ssl_verify off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;
          
          proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        }

        location /{{ .Release.Namespace }}/onboard {
          rewrite ^/{{ .Release.Namespace }}/onboard(.*) /onboard$1 break;

          proxy_pass http://onboard-service.{{ .Release.Namespace }}.svc.cluster.local:6251;
          proxy_ssl_verify off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;

          proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        }

        location /{{ .Release.Namespace }}/inventory {
          rewrite ^/{{ .Release.Namespace }}/inventory(.*) /inventory$1 break;

          proxy_pass http://inventory-service.{{ .Release.Namespace }}.svc.cluster.local:7251;
          proxy_ssl_verify off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;

          proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        }

        location /{{ .Release.Namespace }}/metadata {
          rewrite ^/{{ .Release.Namespace }}/metadata(.*) /metadata$1 break;

          proxy_pass http://metadata-service.{{ .Release.Namespace }}.svc.cluster.local:6251;
          proxy_ssl_verify off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;

          proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        }

        location /{{ .Release.Namespace }}/compliance {
          rewrite ^/{{ .Release.Namespace }}/compliance(.*) /compliance$1 break;

          proxy_pass http://compliance-service.{{ .Release.Namespace }}.svc.cluster.local:7251;
          proxy_ssl_verify off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;

          proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        }

        location /{{ .Release.Namespace }}/schedule {
          rewrite ^/{{ .Release.Namespace }}/schedule(.*) /schedule$1 break;

          proxy_pass http://describe-scheduler.{{ .Release.Namespace }}.svc.cluster.local:5251;
          proxy_ssl_verify off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;

          proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        }

        location /{{ .Release.Namespace }}/auth {
          rewrite ^/{{ .Release.Namespace }}/auth(.*) /auth$1 break;

          proxy_pass http://auth-service.{{ .Release.Namespace }}.svc.cluster.local:8251;
          proxy_ssl_verify off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;

          proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        }

        location /{{ .Release.Namespace }}/workspace {
          rewrite ^/{{ .Release.Namespace }}/workspace(.*) /workspace$1 break;

          proxy_pass http://workspace-service.{{ .Release.Namespace }}.svc.cluster.local:8351;
          proxy_ssl_verify off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;

          proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        }

        location /dex {
          proxy_pass http://kaytu-octopus-dex.{{ .Release.Namespace }}.svc.cluster.local:5556;
          proxy_ssl_verify off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;

          proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        }

        location /kaytu/auth {
          proxy_pass http://auth-service.{{ .Release.Namespace }}.svc.cluster.local:8251;
          proxy_ssl_verify off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;

          proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        }

        location /kaytu/workspace {
          proxy_pass http://workspace-service.{{ .Release.Namespace }}.svc.cluster.local:8351;
          proxy_ssl_verify off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;

          proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        }

        location / {
          proxy_pass http://frontend-v2-svc.{{ .Release.Namespace }}.svc.cluster.local:7298;
          proxy_ssl_verify off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;

          proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        }
      }
    }