apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-oci
  namespace: flux-system
spec:
  interval: 10m0s
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: {{ .Release.Namespace }}
spec:
  interval: 10m0s
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
      version: 15.5.21
  values:
    architecture: replication
    readReplicas:
      replicaCount: {{ .Values.readReplicas.replicaCount }}
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 16.4.0
      pullPolicy: Always
      debug: false
    primary:
      persistence:
        size: 10Gi
      existingConfigmap: postgres-config
      initdb:
        scriptsConfigMap: postgres-init-script
      resources:
        limits:
          memory: {{ .Values.primary.resources.limits.memory }}
          cpu: {{ .Values.primary.resources.limits.cpu }}
        requests:
          memory: {{ .Values.primary.resources.requests.memory }}
          cpu: {{ .Values.primary.resources.requests.cpu }}
      auth:
        existingSecret: postgres-secret
        secretKeys:
          userPasswordKey: superUserPassword
          replicationPasswordKey: replicationUserPassword
      extraEnvVars:
        - name : POSTGRES_DESCRIBE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: describeSchedulerUserPassword
        - name : POSTGRES_ONBOARD_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: onboardServiceUserPassword
        - name : POSTGRES_POLICY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: policyServiceUserPassword
        - name: POSTGRES_INVENTORY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: inventoryServiceUserPassword
        - name: POSTGRES_ASSISTANT_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: assistantServiceUserPassword
        - name: POSTGRES_COMPLIANCE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: complianceServiceUserPassword
        - name: POSTGRES_AUTH_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: authServiceUserPassword
        - name: POSTGRES_METADATA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: metadataServiceUserPassword
        - name: POSTGRES_REPORTER_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: reporterServiceUserPassword
        - name: POSTGRES_MIGRATOR_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: migratorServiceUserPassword
        - name: POSTGRES_EXPORTER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgresExporterUserPassword
        - name: POSTGRES_STEAMPIPE_USER_PASSWORD
          valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: steampipeUserPassword
        - name: POSTGRES_ALERTING_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: alertingServiceUserPassword
