apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v2
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-v2
  template:
    metadata:
      labels:
        app: frontend-v2
    spec:

      containers:
      - name: frontend-v2
        image: "{{ .Values.kaytu.docker.registry }}/kaytu-frontend:{{- dig .Values.kaytu.envType .Values.kaytu.docker.tags.frontendv2.dev .Values.kaytu.docker.tags.frontendv2 }}"
        imagePullPolicy: Always
        ports:
          - containerPort: 7298
        envFrom:
          - configMapRef:
              name: frontend-v2-env
        volumeMounts:
          - mountPath: /usr/share/nginx/html/.env
            name: frontend-v2-env
            subPath: .env
      volumes:
        - name: frontend-v2-env
          configMap:
            name: frontend-v2-env
            items:
              - key: .env
                path: .env

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-v2-env
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend-v2
data:
  .env: |
    NODE_ENV=production
    REACT_APP_NODE_ENV=prod
    REACT_APP_MUI_LICENSE={{ .Values.kaytu.frontend.muiLicense }}
    REACT_APP_AUDIENCE={{ .Values.kaytu.auth0.audience }}
    REACT_APP_AUTH0_AUDIENCE={{ .Values.kaytu.auth0.audience }}
    REACT_APP_AUTH0_DOMAIN="https://{{ .Values.kaytu.auth0.domain }}"
    REACT_APP_AUTH0_CLIENT_ID={{ .Values.kaytu.auth0.clientId }}
    REACT_APP_DOMAIN="https://{{ .Values.kaytu.auth0.domain }}"
    REACT_APP_CLIENT_ID={{ .Values.kaytu.auth0.clientId }}
    REACT_APP_BASE_URL="https://{{ .Values.kaytu.domain.main }}"
    REACT_APP_AUTH_BASE_URL="https://{{ .Values.kaytu.domain.main }}"
  NODE_ENV: production
  REACT_APP_NODE_ENV: prod
  REACT_APP_MUI_LICENSE: {{ .Values.kaytu.frontend.muiLicense }}
  REACT_APP_AUDIENCE: {{ .Values.kaytu.auth0.audience }}
  REACT_APP_AUTH0_AUDIENCE: {{ .Values.kaytu.auth0.audience }}
  REACT_APP_AUTH0_DOMAIN: "https://{{ .Values.kaytu.auth0.domain }}"
  REACT_APP_AUTH0_CLIENT_ID: {{ .Values.kaytu.auth0.clientId }}
  REACT_APP_DOMAIN: "https://{{ .Values.kaytu.auth0.domain }}"
  REACT_APP_CLIENT_ID: {{ .Values.kaytu.auth0.clientId }}
  REACT_APP_BASE_URL: "https://{{ .Values.kaytu.domain.main }}"
  REACT_APP_AUTH_BASE_URL: "https://{{ .Values.kaytu.domain.main }}"
