---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: {{ .Release.Namespace }}
spec:
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      version: 0.28.1
  targetNamespace: {{ .Release.Namespace }}
  releaseName: vault
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  interval: 1m0s
  vaules:
    prometheusRules:
      enabled: true
