---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alerting
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountID }}:role/kaytu-service-{{ .Release.Namespace }}-alerting
---
apiVersion: v1
kind: Secret
metadata:
  name: alerting-secret
  namespace: {{ .Release.Namespace }}

  annotations:
    kubernetes.io/service-account.name: alerting
type: kubernetes.io/service-account-token
