apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: integration-service
spec:
  minReadySeconds: 10
  replicas: {{ .Values.kaytu.replicaCount }}
  selector:
    matchLabels:
      app: integration-service
  template:
    metadata:
      labels:
        app: integration-service
    spec:
      serviceAccountName: integration
      containers:
      - name: integration-service
        image: {{ .Values.kaytu.integration.service.image.repo }}:{{- dig .Values.kaytu.envType .Values.kaytu.integration.service.image.tag.dev .Values.kaytu.integration.service.image.tag }}
        command: ["/integration-service"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 100Mi
        env:
        - name: INTEGRATION_POSTGRES__HOST
          value: {{ .Values.postgres.name }}.{{ .Release.Namespace }}.svc.cluster.local
        - name: INTEGRATION_POSTGRES__PORT
          value: "5432"
        - name: INTEGRATION_POSTGRES__DB
          value: "onboard"
        - name: INTEGRATION_POSTGRES__USERNAME
          value: "onboard_service"
        - name: INTEGRATION_POSTGRES__PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: onboardServiceUserPassword
        - name: INTEGRATION_POSTGRES__SSLMODE
          value: {{ .Values.postgres.sslMode }}
        - name: INTEGRATION_HTTP__ADDRESS
          value: "0.0.0.0:8000"
        - name: INTEGRATION_INVENTORY__BASE_URL
          value: "http://inventory-service.{{ .Release.Namespace }}.svc.cluster.local:7251"
        - name: INTEGRATION_DESCRIBE__BASE_URL
          value: "http://describe-scheduler.{{ .Release.Namespace }}.svc.cluster.local:5251"
        - name: INTEGRATION_METADATA__BASE_URL
          value: "http://metadata-service.{{ .Release.Namespace }}.svc.cluster.local:6251"

        - name: INTEGRATION_VAULT__PROVIDER
          value: {{ .Values.vault.provider }}
        - name: INTEGRATION_VAULT__AWS__REGION
          value: {{ .Values.vault.aws.region }}
        - name: INTEGRATION_VAULT__AWS__ROLE_ARN
          value: {{ .Values.vault.aws.roleArn }}
        - name: INTEGRATION_VAULT__AWS__ACCESS_KEY
          value: {{ .Values.vault.aws.accessKey }}
        - name: INTEGRATION_VAULT__AWS__SECRET_KEY
          value: {{ .Values.vault.aws.secretKey }}
        - name: INTEGRATION_VAULT__AZURE__BASE_URL
          value: {{ .Values.vault.azure.baseUrl }}
        - name: INTEGRATION_VAULT__AZURE__CLIENT_ID
          value: {{ .Values.vault.azure.clientId }}
        - name: INTEGRATION_VAULT__AZURE__TENANT_ID
          value: {{ .Values.vault.azure.tenantId }}
        - name: INTEGRATION_VAULT__AZURE__CLIENT_SECRET
          value: {{ .Values.vault.azure.clientSecret }}
        - name: INTEGRATION_VAULT__HASHICORP__ADDRESS
          value: "http://vault-internal.vault-system.svc.cluster.local:8200"
        - name: INTEGRATION_VAULT__KEY_ID
          value: {{ .Values.vault.keyID }}

        - name: INTEGRATION_MASTER_ACCESS_KEY
          value: {{ .Values.kaytu.workspace.masterAccessKey }}
        - name: INTEGRATION_MASTER_SECRET_KEY
          value: {{ .Values.kaytu.workspace.masterSecretKey }}
        - name: INTEGRATION_JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: INTEGRATION_JAEGER_SERVICE_NAME
          value: "integration-service"
        - name: INTEGRATION_JAEGER_SAMPLE_RATE
          value: "0.005"
