apiVersion: v1
kind: ConfigMap
metadata:
  name: kaytu-version
  namespace: {{ .Release.Namespace }}
data:
  version: "{{- dig .Values.kaytu.envType .Values.kaytu.inventory.service.image.tag.dev .Values.kaytu.inventory.service.image.tag }}"