{{- if eq .Release.Namespace "ws-461045852610243491" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporter-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: reporter-service
spec:
  replicas: 0
  selector:
    matchLabels:
      app: reporter-service
  template:
    metadata:
      labels:
        app: reporter-service
    spec:
      serviceAccountName: reporter
      imagePullSecrets:
        - name: kaytu
      containers:
        - name: reporter
          image: {{ .Values.kaytu.reporter.image.repo }}:{{- dig .Values.kaytu.envType .Values.kaytu.reporter.image.tag.dev .Values.kaytu.reporter.image.tag }}
          command: ["/reporter"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
          - name: STEAMPIPE_HOST
            value: steampipe-service.{{ .Release.Namespace }}.svc.cluster.local
          - name: STEAMPIPE_PORT
            value: "9193"
          - name: STEAMPIPE_USERNAME
            value: "steampipe"
          - name: STEAMPIPE_PASSWORD
            value: "abcd"
          - name: STEAMPIPE_DB
            value: "steampipe"

          - name: DATABASE_HOST
            value: {{ .Release.Namespace }}-postgresql-primary.{{ .Release.Namespace }}.svc.cluster.local
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_USERNAME
            value: "reporter_service"
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: reporterServiceUserPassword
          - name: DATABASE_DB
            value: "reporter"
          - name: DATABASE_SSLMODE
            value: {{ .Values.postgres.sslMode }}

          - name: STEAMPIPEES_HOST
            value: steampipe-service.{{ .Release.Namespace }}.svc.cluster.local
          - name: STEAMPIPEES_PORT
            value: "9193"
          - name: STEAMPIPEES_USERNAME
            value: "steampipe"
          - name: STEAMPIPEES_PASSWORD
            value: "abcd"
          - name: STEAMPIPEES_DB
            value: "steampipe"

          - name: ONBOARD_BASEURL
            value: "http://onboard-service.{{ .Release.Namespace }}.svc.cluster.local:6251"
          - name: SCHEDULEMINUTES
            value: "15"

          - name: HTTP_ADDRESS
            value: "0.0.0.0:9251"

          - name: JAEGER_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: JAEGER_SERVICE_NAME
            value: "reporter-service"

          volumeMounts:
            - name: report-queries
              mountPath: /queries-aws.json
              subPath: queries-aws.json
            - name: report-queries
              mountPath: /queries-azure.json
              subPath: queries-azure.json
      volumes:
        - name: report-queries
          configMap:
            name: report-queries-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: report-queries-config
  namespace: {{ .Release.Namespace }}
data:
  queries-aws.json: |
    [
      {
        "keyFields": ["arn"],
        "tableName": "aws_ec2_instance",
        "steampipe_query": "SELECT * FROM aws_ec2_instance",
        "elastic_search_query": "SELECT * FROM aws_ec2_instance WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_vpc",
        "steampipe_query": "SELECT * FROM aws_vpc;",
        "elastic_search_query": "SELECT * FROM aws_vpc WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["route_table_id"],
        "tableName": "aws_vpc_route_table",
        "steampipe_query": "SELECT * FROM aws_vpc_route_table",
        "elastic_search_query": "SELECT * FROM aws_vpc_route_table WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND route_table_id = $1"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_ebs_volume",
        "steampipe_query": "SELECT * FROM aws_ebs_volume",
        "elastic_search_query": "SELECT * FROM aws_ebs_volume WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["name"],
        "tableName": "aws_s3_bucket",
        "steampipe_query": "SELECT * FROM aws_s3_bucket",
        "elastic_search_query": "SELECT * FROM aws_s3_bucket WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND name = $1"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_backup_vault",
        "steampipe_query": "SELECT * FROM aws_backup_vault",
        "elastic_search_query": "SELECT * FROM aws_backup_vault WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["name"],
        "tableName": "aws_cloudformation_stack",
        "steampipe_query": "SELECT * FROM aws_cloudformation_stack",
        "elastic_search_query": "SELECT * FROM aws_cloudformation_stack WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND name = $1"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_ecr_repository",
        "steampipe_query": "SELECT * FROM aws_ecr_repository",
        "elastic_search_query": "SELECT * FROM aws_ecr_repository WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_ebs_snapshot",
        "steampipe_query": "SELECT * FROM aws_ebs_snapshot",
        "elastic_search_query": "SELECT * FROM aws_ebs_snapshot WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_ec2_application_load_balancer",
        "steampipe_query": "SELECT * FROM aws_ec2_application_load_balancer",
        "elastic_search_query": "SELECT * FROM aws_ec2_application_load_balancer WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_ec2_classic_load_balancer",
        "steampipe_query": "SELECT * FROM aws_ec2_classic_load_balancer",
        "elastic_search_query": "SELECT * FROM aws_ec2_classic_load_balancer WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_ec2_network_load_balancer",
        "steampipe_query": "SELECT * FROM aws_ec2_network_load_balancer",
        "elastic_search_query": "SELECT * FROM aws_ec2_network_load_balancer WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_ec2_gateway_load_balancer",
        "steampipe_query": "SELECT * FROM aws_ec2_gateway_load_balancer",
        "elastic_search_query": "SELECT * FROM aws_ec2_gateway_load_balancer WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_eks_cluster",
        "steampipe_query": "SELECT * FROM aws_eks_cluster",
        "elastic_search_query": "SELECT * FROM aws_eks_cluster WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_lambda_function",
        "steampipe_query": "SELECT * FROM aws_lambda_function",
        "elastic_search_query": "SELECT * FROM aws_lambda_function WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_rds_db_cluster",
        "steampipe_query": "SELECT * FROM aws_rds_db_cluster",
        "elastic_search_query": "SELECT * FROM aws_rds_db_cluster WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_vpc_eip",
        "steampipe_query": "SELECT * FROM aws_vpc_eip",
        "elastic_search_query": "SELECT * FROM aws_vpc_eip WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_rds_db_instance",
        "steampipe_query": "SELECT * FROM aws_rds_db_instance",
        "elastic_search_query": "SELECT * FROM aws_rds_db_instance WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["fargate_profile_arn"],
        "tableName": "aws_eks_fargate_profile",
        "steampipe_query": "SELECT * FROM aws_eks_fargate_profile",
        "elastic_search_query": "SELECT * FROM aws_eks_fargate_profile WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND fargate_profile_arn = $1"
      },
      {
        "keyFields": ["title", "cluster_name", "region"],
        "tableName": "aws_eks_node_group",
        "steampipe_query": "SELECT * FROM aws_eks_node_group",
        "elastic_search_query": "SELECT * FROM aws_eks_node_group WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND title = $1 AND cluster_name = $2 AND region = $3"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_vpc_security_group",
        "steampipe_query": "SELECT * FROM aws_vpc_security_group",
        "elastic_search_query": "SELECT * FROM aws_vpc_security_group WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["user_name"],
        "tableName": "aws_iam_access_key",
        "steampipe_query": "SELECT * FROM aws_iam_access_key",
        "elastic_search_query": "SELECT * FROM aws_iam_access_key WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND user_name = $1"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_iam_role",
        "steampipe_query": "SELECT * FROM aws_iam_role",
        "elastic_search_query": "SELECT * FROM aws_iam_role WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_iam_user",
        "steampipe_query": "SELECT * FROM aws_iam_user",
        "elastic_search_query": "SELECT * FROM aws_iam_user WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      },
      {
        "keyFields": ["arn"],
        "tableName": "aws_iam_group",
        "steampipe_query": "SELECT * FROM aws_iam_group",
        "elastic_search_query": "SELECT * FROM aws_iam_group WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND arn = $1"
      }
    ]
  queries-azure.json: |
    [
      {
        "keyFields": ["id"],
        "tableName": "azure_network_interface",
        "steampipe_query": "SELECT * FROM azure_network_interface",
        "elastic_search_query": "SELECT * FROM azure_network_interface WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_application_gateway",
        "steampipe_query": "SELECT * FROM azure_application_gateway",
        "elastic_search_query": "SELECT * FROM azure_application_gateway WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_automation_account",
        "steampipe_query": "SELECT * FROM azure_automation_account",
        "elastic_search_query": "SELECT * FROM azure_automation_account WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_recovery_services_vault",
        "steampipe_query": "SELECT * FROM azure_recovery_services_vault",
        "elastic_search_query": "SELECT * FROM azure_recovery_services_vault WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_container_registry",
        "steampipe_query": "SELECT * FROM azure_container_registry",
        "elastic_search_query": "SELECT * FROM azure_container_registry WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_cosmosdb_account",
        "steampipe_query": "SELECT * FROM azure_cosmosdb_account",
        "elastic_search_query": "SELECT * FROM azure_cosmosdb_account WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_mssql_managed_instance",
        "steampipe_query": "SELECT * FROM azure_mssql_managed_instance",
        "elastic_search_query": "SELECT * FROM azure_mssql_managed_instance WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_mysql_server",
        "steampipe_query": "SELECT * FROM azure_mysql_server",
        "elastic_search_query": "SELECT * FROM azure_mysql_server WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_postgresql_server",
        "steampipe_query": "SELECT * FROM azure_postgresql_server",
        "elastic_search_query": "SELECT * FROM azure_postgresql_server WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_sql_database",
        "steampipe_query": "SELECT * FROM azure_sql_database",
        "elastic_search_query": "SELECT * FROM azure_sql_database WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_sql_database",
        "steampipe_query": "SELECT * FROM azure_sql_database",
        "elastic_search_query": "SELECT * FROM azure_sql_database WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_sql_server",
        "steampipe_query": "SELECT * FROM azure_sql_server",
        "elastic_search_query": "SELECT * FROM azure_sql_server WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_kubernetes_cluster",
        "steampipe_query": "SELECT * FROM azure_kubernetes_cluster",
        "elastic_search_query": "SELECT * FROM azure_kubernetes_cluster WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_compute_virtual_machine",
        "steampipe_query": "SELECT * FROM azure_compute_virtual_machine",
        "elastic_search_query": "SELECT * FROM azure_compute_virtual_machine WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_compute_virtual_machine",
        "steampipe_query": "SELECT * FROM azure_compute_virtual_machine",
        "elastic_search_query": "SELECT * FROM azure_compute_virtual_machine WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_virtual_network",
        "steampipe_query": "SELECT * FROM azure_virtual_network",
        "elastic_search_query": "SELECT * FROM azure_virtual_network WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_subnet",
        "steampipe_query": "SELECT * FROM azure_subnet",
        "elastic_search_query": "SELECT * FROM azure_subnet WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_resource_group",
        "steampipe_query": "SELECT * FROM azure_resource_group",
        "elastic_search_query": "SELECT * FROM azure_resource_group WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_route_table",
        "steampipe_query": "SELECT * FROM azure_route_table",
        "elastic_search_query": "SELECT * FROM azure_route_table WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      },
      {
        "keyFields": ["id"],
        "tableName": "azure_lb",
        "steampipe_query": "SELECT * FROM azure_lb",
        "elastic_search_query": "SELECT * FROM azure_lb WHERE kaytu_account_id = '%KAYTU_ACCOUNT_ID%' AND id = $1"
      }
    ]
{{ end }}