apiVersion: apps/v1
kind: Deployment
metadata:
  name: area51
  namespace: {{ .Release.Namespace }}
  labels:
    app: area51
spec:
  replicas: 1
  selector:
    matchLabels:
      app: area51
  template:
    metadata:
      labels:
        app: area51
    spec:

      containers:
      - name: website
        image: "{{ .Values.kaytu.docker.registry }}/website-v2:{{- dig .Values.kaytu.envType .Values.kaytu.docker.tags.area51.dev .Values.kaytu.docker.tags.area51 }}"
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        envFrom:
          - configMapRef:
              name: website-env
        volumeMounts:
          - mountPath: /usr/share/nginx/html/.env
            name: website-env
            subPath: .env
      volumes:
        - name: website-env
          configMap:
            name: website-env
            items:
              - key: .env
                path: .env
