apiVersion: v1
kind: Service
metadata:
  name: website-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: website
spec:
  selector:
    app: website
  ports:
  - port: 7300
    targetPort: 3000
  clusterIP: "None"
---
apiVersion: v1
kind: Service
metadata:
  name: area51-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: area51
spec:
  selector:
    app: area51
  ports:
    - port: 7300
      targetPort: 3000
  clusterIP: "None"