apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: {{ .Release.Namespace }}
  labels:
    app: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:

      containers:
      - name: website
        image: "{{ .Values.kaytu.docker.registry }}/website-v2:{{- dig .Values.kaytu.envType .Values.kaytu.docker.tags.website.dev .Values.kaytu.docker.tags.website }}"
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        envFrom:
          - configMapRef:
              name: website-env
        volumeMounts:
          - mountPath: /usr/share/nginx/html/.env
            name: website-env
            subPath: .env
      volumes:
        - name: website-env
          configMap:
            name: website-env
            items:
              - key: .env
                path: .env

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: website-env
  namespace: {{ .Release.Namespace }}
  labels:
    app: website
data:
  .env: |
    NODE_ENV=production
    REACT_APP_NODE_ENV=prod
    REACT_APP_MUI_LICENSE={{ .Values.kaytu.frontend.muiLicense }}
    REACT_APP_AUDIENCE={{ .Values.kaytu.auth0.audience }}
    REACT_APP_AUTH0_AUDIENCE={{ .Values.kaytu.auth0.audience }}
    REACT_APP_AUTH0_DOMAIN="https://{{ .Values.kaytu.auth0.domain }}"
    REACT_APP_AUTH0_CLIENT_ID={{ .Values.kaytu.auth0.clientId }}
    REACT_APP_DOMAIN="https://{{ .Values.kaytu.auth0.domain }}"
    REACT_APP_CLIENT_ID={{ .Values.kaytu.auth0.clientId }}
    REACT_APP_BASE_URL="https://{{ .Values.kaytu.domain.appv2 }}"
  NODE_ENV: production
  REACT_APP_NODE_ENV: prod
  REACT_APP_MUI_LICENSE: {{ .Values.kaytu.frontend.muiLicense }}
  REACT_APP_AUDIENCE: {{ .Values.kaytu.auth0.audience }}
  REACT_APP_AUTH0_AUDIENCE: {{ .Values.kaytu.auth0.audience }}
  REACT_APP_AUTH0_DOMAIN: "https://{{ .Values.kaytu.auth0.domain }}"
  REACT_APP_AUTH0_CLIENT_ID: {{ .Values.kaytu.auth0.clientId }}
  REACT_APP_DOMAIN: "https://{{ .Values.kaytu.auth0.domain }}"
  REACT_APP_CLIENT_ID: {{ .Values.kaytu.auth0.clientId }}
  REACT_APP_BASE_URL: "https://{{ .Values.kaytu.domain.appv2 }}"