{{- $superUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $replicationUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $describeSchedulerUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $onboardServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $policyServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $inventoryServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $complianceServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $authServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $metadataServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $migratorServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $reporterServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $postgresExporterUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $steampipeUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $alertingServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $assistantServiceUserPassword := (randAlpha 16) | b64enc | quote }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace "postgres-secret") }}
{{- if $secret }}
{{- $superUserPassword = index $secret.data "superUserPassword" | default $superUserPassword }}
{{- $replicationUserPassword = index $secret.data "replicationUserPassword" | default $replicationUserPassword }}
{{- $describeSchedulerUserPassword = index $secret.data "describeSchedulerUserPassword" | default $describeSchedulerUserPassword }}
{{- $onboardServiceUserPassword = index $secret.data "onboardServiceUserPassword" | default $onboardServiceUserPassword }}
{{- $policyServiceUserPassword = index $secret.data "policyServiceUserPassword" | default $policyServiceUserPassword }}
{{- $inventoryServiceUserPassword = index $secret.data "inventoryServiceUserPassword" | default $inventoryServiceUserPassword }}
{{- $complianceServiceUserPassword = index $secret.data "complianceServiceUserPassword" | default $complianceServiceUserPassword }}
{{- $authServiceUserPassword = index $secret.data "authServiceUserPassword" | default $authServiceUserPassword }}
{{- $metadataServiceUserPassword = index $secret.data "metadataServiceUserPassword" | default $metadataServiceUserPassword }}
{{- $migratorServiceUserPassword = index $secret.data "migratorServiceUserPassword" | default $migratorServiceUserPassword }}
{{- $reporterServiceUserPassword = index $secret.data "reporterServiceUserPassword" | default $reporterServiceUserPassword }}
{{- $postgresExporterUserPassword = index $secret.data "postgresExporterUserPassword" | default $postgresExporterUserPassword }}
{{- $steampipeUserPassword = index $secret.data "steampipeUserPassword" | default $steampipeUserPassword }}
{{- $alertingServiceUserPassword = index $secret.data "alertingServiceUserPassword" | default $alertingServiceUserPassword}}
{{- $assistantServiceUserPassword = index $secret.data "assistantServiceUserPassword" | default $assistantServiceUserPassword}}
{{- end -}}


apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  superUserPassword: {{ $superUserPassword }}
  replicationUserPassword: {{ $replicationUserPassword }}
  describeSchedulerUserPassword: {{ $describeSchedulerUserPassword }}
  onboardServiceUserPassword: {{ $onboardServiceUserPassword }}
  policyServiceUserPassword: {{ $policyServiceUserPassword }}
  inventoryServiceUserPassword: {{ $inventoryServiceUserPassword }}
  complianceServiceUserPassword: {{ $complianceServiceUserPassword }}
  authServiceUserPassword: {{ $authServiceUserPassword }}
  metadataServiceUserPassword: {{ $metadataServiceUserPassword }}
  migratorServiceUserPassword: {{ $migratorServiceUserPassword }}
  reporterServiceUserPassword: {{ $reporterServiceUserPassword }}
  postgresExporterUserPassword: {{ $postgresExporterUserPassword }}
  steampipeUserPassword: {{ $steampipeUserPassword }}
  alertingServiceUserPassword: {{ $alertingServiceUserPassword }}
  assistantServiceUserPassword: {{ $assistantServiceUserPassword }}