apiVersion: apps/v1
kind: Deployment
metadata:
  name: redoc
  namespace: {{ .Release.Namespace }}
  labels:
    app: redoc
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: redoc
  template:
    metadata:
      labels:
        app: redoc
    spec:

      containers:
      - name: redoc
        image: "{{ .Values.kaytu.docker.registry }}/redoc:{{- dig .Values.kaytu.envType .Values.kaytu.docker.tags.redoc.dev .Values.kaytu.docker.tags.redoc }}"
        imagePullPolicy: Always
        env:
        - name: HTTP_ADDRESS
          value: "0.0.0.0:8080"
