apiVersion: v1
kind: Service
metadata:
  name: redoc
  namespace: {{ .Release.Namespace }}
  labels:
    app: redoc
spec:
  selector:
    app: redoc
  ports:
  - port: 8080
    targetPort: 8080
  clusterIP: "None"