{{- if eq (.Values.kaytu.envType | toString) "dev" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pennywise-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: pennywise-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pennywise-server
  template:
    metadata:
      labels:
        app: pennywise-server
    spec:
      containers:
        - name: integration-service
          image: "{{ .Values.kaytu.docker.registry }}/pennywise-server:{{- dig .Values.kaytu.envType .Values.kaytu.docker.tags.pennywise.dev .Values.kaytu.docker.tags.pennywise }}"
          command: ["./main"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.postgres.name }}.{{ .Release.Namespace }}.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "pennywise"
            - name: POSTGRES_USERNAME
              value: "pennywise_service"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: pennywiseUserPassword
{{- end }}