apiVersion: v1
kind: Service
metadata:
  name: subscription-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: subscription-service
    monitoring: kaytu
spec:
  selector:
    app: subscription-service
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  clusterIP: "None"