apiVersion: v1
kind: ServiceAccount
metadata:
  name: workspace-service
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.kaytu.vault.aws.roleArn }}
---
apiVersion: v1
kind: Secret
metadata:
  name: workspace-service-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: workspace-service
type: kubernetes.io/service-account-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: workspace-service
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: workspace-service
  template:
    metadata:
      labels:
        app: workspace-service
    spec:
      serviceAccountName: workspace-service

      containers:
        - name: workspace-service
          image: "{{ .Values.kaytu.docker.registry }}/workspace-service:{{- dig .Values.kaytu.envType .Values.kaytu.docker.tags.workspace.dev .Values.kaytu.docker.tags.workspace }}"
          command: [ "/workspace-service" ]
          imagePullPolicy: Always
          env:
            - name: WORKSPACE_ENV_TYPE
              value: {{ .Values.kaytu.envType }}
            - name: WORKSPACE_POSTGRES__HOST
              value: {{ .Release.Namespace }}-postgresql-primary.{{ .Release.Namespace }}.svc.cluster.local
            - name: WORKSPACE_POSTGRES__PORT
              value: "5432"
            - name: WORKSPACE_POSTGRES__DB
              value: "workspace"
            - name: WORKSPACE_POSTGRES__USERNAME
              value: "workspace_service"
            - name: WORKSPACE_POSTGRES__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: workspaceServiceUserPassword
            - name: WORKSPACE_POSTGRES_SSL_MODE
              value: {{ .Values.postgres.sslMode }}
            - name: WORKSPACE_HTTP__ADDRESS
              value: "0.0.0.0:8351"
            - name: WORKSPACE_DOMAIN_SUFFIX
              value: "{{ .Values.kaytu.domain.main }}"
            - name: WORKSPACE_APP_DOMAIN
              value: "{{ .Values.kaytu.domain.main }}"
            - name: WORKSPACE_GRPC_DOMAIN
              value: "{{ .Values.kaytu.domain.grpc }}"
            - name: WORKSPACE_GRPC_EXTERNAL_DOMAIN
              value: "{{ .Values.kaytu.domain.grpc_external }}"
            - name: WORKSPACE_AUTH__BASE_URL
              value: "http://auth-service.{{ .Release.Namespace }}.svc.cluster.local:8251"
            - name: WORKSPACE_ONBOARD__BASE_URL
              value: "http://onboard-service.%NAMESPACE%.svc.cluster.local:6251"
            - name: WORKSPACE_SCHEDULER__BASE_URL
              value: "http://describe-scheduler.%NAMESPACE%.svc.cluster.local:5251"
            - name: WORKSPACE_COMPLIANCE__BASE_URL
              value: "http://compliance-service.%NAMESPACE%.svc.cluster.local:7251"
            - name: WORKSPACE_INVENTORY__BASE_URL
              value: "http://inventory-service.%NAMESPACE%.svc.cluster.local:7251"
            - name: WORKSPACE_AUTO_SUSPEND_DURATION_MINUTES
              value: "60"
            - name: WORKSPACE_KAYTU_HELM_CHART_LOCATION
              value: "{{ .Values.kaytu.workspace.kaytuChartLocation }}"
            - name: WORKSPACE_KAYTU_OCTOPUS_NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: WORKSPACE_FLUX_SYSTEM_NAMESPACE
              value: "{{ .Values.flux.namespace }}"
            - name: WORKSPACE_VAULT__PROVIDER
              value: {{ .Values.kaytu.vault.provider }}
            - name: WORKSPACE_VAULT__AWS__REGION
              value: {{ .Values.kaytu.vault.aws.region }}
            - name: WORKSPACE_VAULT__AWS__ROLE_ARN
              value: {{ .Values.kaytu.vault.aws.roleArn }}
            - name: WORKSPACE_VAULT__AWS__ACCESS_KEY
              value: {{ .Values.kaytu.vault.aws.accessKey }}
            - name: WORKSPACE_VAULT__AWS__SECRET_KEY
              value: {{ .Values.kaytu.vault.aws.secretKey }}
            - name: WORKSPACE_VAULT__AZURE__BASE_URL
              value: {{ .Values.kaytu.vault.azure.baseUrl }}
            - name: WORKSPACE_VAULT__AZURE__CLIENT_ID
              value: {{ .Values.kaytu.vault.azure.clientId }}
            - name: WORKSPACE_VAULT__AZURE__TENANT_ID
              value: {{ .Values.kaytu.vault.azure.tenantId }}
            - name: WORKSPACE_VAULT__AZURE__CLIENT_SECRET
              value: {{ .Values.kaytu.vault.azure.clientSecret }}
            - name: WORKSPACE_VAULT__HASHICORP__ADDRESS
              value: "http://{{ .Release.Namespace }}-vault-internal.{{ .Release.Namespace }}.svc.cluster.local:8200"
            - name: WORKSPACE_VAULT__KEY_ID
              value: {{ .Values.kaytu.vault.keyID }}


            - name: WORKSPACE_AWS_MASTER_POLICY_ARN
              value: "{{ .Values.kaytu.master.policyARN }}"

            - name: WORKSPACE_OPEN_SEARCH_REGION
              value: "us-east-2"
            - name: WORKSPACE_AWS_ACCOUNT_ID
              value: "{{ .Values.kaytu.master.accountID }}"
            - name: WORKSPACE_OIDC_PROVIDER
              value: "{{ .Values.kaytu.master.oidcProvider }}"
            - name: WORKSPACE_MASTER_ROLE_ARN
              value: "{{ .Values.kaytu.master.masterRoleARN }}"
            - name: WORKSPACE_SECURITY_GROUP_ID
              value: "{{ .Values.kaytu.master.securityGroupID }}"
            - name: WORKSPACE_SUBNET_ID
              value: "{{ .Values.kaytu.master.subnetID }}"
            - name: WORKSPACE_DO_RESERVE
              value: "false"
            - name: WORKSPACE_KAYTU_WORKSPACE_VERSION
              value: "{{ .Values.kaytu.workspace.chart.version }}"
