apiVersion: v1
kind: Service
metadata:
  name: docs-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: docs
spec:
  selector:
    app: docs
  ports:
  - port: 80
    targetPort: 80
  clusterIP: "None"