readReplicas:
  replicaCount: 1
image:
  tag: 16.4.0
primary:
  resources:
    limits:
      memory: "3Gi"
      cpu: "3"
    requests:
      memory: "1.5Gi"
      cpu: "1"
config: |
  listen_addresses = '*'
  max_wal_senders = 10
  shared_preload_libraries = 'pg_stat_statements'
  
  max_connections = 40
  shared_buffers = 768MB
  effective_cache_size = 2304MB
  maintenance_work_mem = 384MB
  checkpoint_completion_target = 0.9
  wal_buffers = 16MB
  default_statistics_target = 500
  random_page_cost = 1.1
  effective_io_concurrency = 200
  work_mem = 4915kB
  huge_pages = off
  min_wal_size = 4GB
  max_wal_size = 16GB